export type Country = {
  code: string;
  name: string;
  phoneCode: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { code: "PL", name: "Polska", phoneCode: "+48", flag: "PL" },
  { code: "AF", name: "Afganistan", phoneCode: "+93", flag: "AF" },
  { code: "AL", name: "Albania", phoneCode: "+355", flag: "AL" },
  { code: "DZ", name: "Algieria", phoneCode: "+213", flag: "DZ" },
  { code: "AR", name: "Argentyna", phoneCode: "+54", flag: "AR" },
  { code: "AU", name: "Australia", phoneCode: "+61", flag: "AU" },
  { code: "AT", name: "Austria", phoneCode: "+43", flag: "AT" },
  { code: "BE", name: "Belgia", phoneCode: "+32", flag: "BE" },
  { code: "BY", name: "Bialorus", phoneCode: "+375", flag: "BY" },
  { code: "BA", name: "Bosnia i Hercegowina", phoneCode: "+387", flag: "BA" },
  { code: "BR", name: "Brazylia", phoneCode: "+55", flag: "BR" },
  { code: "BG", name: "Bulgaria", phoneCode: "+359", flag: "BG" },
  { code: "CL", name: "Chile", phoneCode: "+56", flag: "CL" },
  { code: "CN", name: "Chiny", phoneCode: "+86", flag: "CN" },
  { code: "HR", name: "Chorwacja", phoneCode: "+385", flag: "HR" },
  { code: "CY", name: "Cypr", phoneCode: "+357", flag: "CY" },
  { code: "ME", name: "Czarnogora", phoneCode: "+382", flag: "ME" },
  { code: "CZ", name: "Czechy", phoneCode: "+420", flag: "CZ" },
  { code: "DK", name: "Dania", phoneCode: "+45", flag: "DK" },
  { code: "EG", name: "Egipt", phoneCode: "+20", flag: "EG" },
  { code: "EC", name: "Ekwador", phoneCode: "+593", flag: "EC" },
  { code: "EE", name: "Estonia", phoneCode: "+372", flag: "EE" },
  { code: "FI", name: "Finlandia", phoneCode: "+358", flag: "FI" },
  { code: "FR", name: "Francja", phoneCode: "+33", flag: "FR" },
  { code: "GR", name: "Grecja", phoneCode: "+30", flag: "GR" },
  { code: "GE", name: "Gruzja", phoneCode: "+995", flag: "GE" },
  { code: "ES", name: "Hiszpania", phoneCode: "+34", flag: "ES" },
  { code: "NL", name: "Holandia", phoneCode: "+31", flag: "NL" },
  { code: "IN", name: "Indie", phoneCode: "+91", flag: "IN" },
  { code: "ID", name: "Indonezja", phoneCode: "+62", flag: "ID" },
  { code: "IQ", name: "Irak", phoneCode: "+964", flag: "IQ" },
  { code: "IR", name: "Iran", phoneCode: "+98", flag: "IR" },
  { code: "IE", name: "Irlandia", phoneCode: "+353", flag: "IE" },
  { code: "IS", name: "Islandia", phoneCode: "+354", flag: "IS" },
  { code: "IL", name: "Izrael", phoneCode: "+972", flag: "IL" },
  { code: "JP", name: "Japonia", phoneCode: "+81", flag: "JP" },
  { code: "CA", name: "Kanada", phoneCode: "+1", flag: "CA" },
  { code: "KZ", name: "Kazachstan", phoneCode: "+7", flag: "KZ" },
  { code: "CO", name: "Kolumbia", phoneCode: "+57", flag: "CO" },
  { code: "KR", name: "Korea Poludniowa", phoneCode: "+82", flag: "KR" },
  { code: "LT", name: "Litwa", phoneCode: "+370", flag: "LT" },
  { code: "LU", name: "Luksemburg", phoneCode: "+352", flag: "LU" },
  { code: "LV", name: "Lotwa", phoneCode: "+371", flag: "LV" },
  { code: "MK", name: "Macedonia Polnocna", phoneCode: "+389", flag: "MK" },
  { code: "MY", name: "Malezja", phoneCode: "+60", flag: "MY" },
  { code: "MT", name: "Malta", phoneCode: "+356", flag: "MT" },
  { code: "MA", name: "Maroko", phoneCode: "+212", flag: "MA" },
  { code: "MX", name: "Meksyk", phoneCode: "+52", flag: "MX" },
  { code: "MD", name: "Moldawia", phoneCode: "+373", flag: "MD" },
  { code: "DE", name: "Niemcy", phoneCode: "+49", flag: "DE" },
  { code: "NO", name: "Norwegia", phoneCode: "+47", flag: "NO" },
  { code: "NZ", name: "Nowa Zelandia", phoneCode: "+64", flag: "NZ" },
  { code: "PK", name: "Pakistan", phoneCode: "+92", flag: "PK" },
  { code: "PE", name: "Peru", phoneCode: "+51", flag: "PE" },
  { code: "PT", name: "Portugalia", phoneCode: "+351", flag: "PT" },
  { code: "RO", name: "Rumunia", phoneCode: "+40", flag: "RO" },
  { code: "RU", name: "Rosja", phoneCode: "+7", flag: "RU" },
  { code: "RS", name: "Serbia", phoneCode: "+381", flag: "RS" },
  { code: "SG", name: "Singapur", phoneCode: "+65", flag: "SG" },
  { code: "SK", name: "Slowacja", phoneCode: "+421", flag: "SK" },
  { code: "SI", name: "Slowenia", phoneCode: "+386", flag: "SI" },
  { code: "US", name: "Stany Zjednoczone", phoneCode: "+1", flag: "US" },
  { code: "CH", name: "Szwajcaria", phoneCode: "+41", flag: "CH" },
  { code: "SE", name: "Szwecja", phoneCode: "+46", flag: "SE" },
  { code: "TH", name: "Tajlandia", phoneCode: "+66", flag: "TH" },
  { code: "TN", name: "Tunezja", phoneCode: "+216", flag: "TN" },
  { code: "TR", name: "Turcja", phoneCode: "+90", flag: "TR" },
  { code: "UA", name: "Ukraina", phoneCode: "+380", flag: "UA" },
  { code: "UY", name: "Urugwaj", phoneCode: "+598", flag: "UY" },
  { code: "VN", name: "Wietnam", phoneCode: "+84", flag: "VN" },
  { code: "GB", name: "Wielka Brytania", phoneCode: "+44", flag: "GB" },
  { code: "HU", name: "Wegry", phoneCode: "+36", flag: "HU" },
  { code: "IT", name: "Wlochy", phoneCode: "+39", flag: "IT" },
  { code: "AE", name: "Zjednoczone Emiraty Arabskie", phoneCode: "+971", flag: "AE" },
  { code: "ZA", name: "Republika Poludniowej Afryki", phoneCode: "+27", flag: "ZA" },
];

export const POLISH_CITIES: string[] = [
  "Aleksandrow Lodzki",
  "Andrychow",
  "Augustow",
  "Bartoszyce",
  "Bedzin",
  "Belchatow",
  "Bialystok",
  "Biala Podlaska",
  "Bielsko-Biala",
  "Bierun",
  "Bilgoraj",
  "Bochnia",
  "Boguszow-Gorce",
  "Boleslawiec",
  "Braniewo",
  "Brodnica",
  "Brzeg",
  "Brzeszcze",
  "Brzeziny",
  "Bukowno",
  "Busko-Zdroj",
  "Bydgoszcz",
  "Bytom",
  "Bytow",
  "Chelm",
  "Chelmno",
  "Chelmza",
  "Chodziez",
  "Chojnice",
  "Chorzow",
  "Choszczno",
  "Cieszyn",
  "Czarnkow",
  "Czechowice-Dziedzice",
  "Czeladz",
  "Czestochowa",
  "Czerwionka-Leszczyny",
  "Czersk",
  "Dabrowka Gornicza",
  "Dabrowa Gornicza",
  "Debica",
  "Deblin",
  "Drawsko Pomorskie",
  "Dzialoszyn",
  "Dzierzoniow",
  "Elblag",
  "Elk",
  "Garwolin",
  "Gdansk",
  "Gdynia",
  "Gizycko",
  "Gliwice",
  "Glogow",
  "Glowno",
  "Glucholazy",
  "Gniezno",
  "Goldap",
  "Goleniow",
  "Gorzow Wielkopolski",
  "Gostyn",
  "Gostynin",
  "Gorlice",
  "Grodzisk Mazowiecki",
  "Grodzisk Wielkopolski",
  "Grojec",
  "Grudziadz",
  "Gryfice",
  "Gryfino",
  "Gubin",
  "Hajnowka",
  "Ilawa",
  "Inowroclaw",
  "Jarocin",
  "Jaroslaw",
  "Jaslo",
  "Jastrzebie-Zdroj",
  "Jawor",
  "Jaworzno",
  "Jelcz-Laskowice",
  "Jelenia Gora",
  "Kalisz",
  "Kamienna Gora",
  "Kamieniec",
  "Karczew",
  "Kartuzy",
  "Katowice",
  "Kazimierz Dolny",
  "Kepno",
  "Ketrzyn",
  "Kielce",
  "Klodzko",
  "Kluczbork",
  "Knurow",
  "Kolobrzeg",
  "Koluszki",
  "Konin",
  "Konstancin-Jeziorna",
  "Konskie",
  "Kostrzyn nad Odra",
  "Koszalin",
  "Koscian",
  "Koscierzyna",
  "Kozienice",
  "Krakow",
  "Krasnik",
  "Krasnystaw",
  "Krosno",
  "Krotoszyn",
  "Kudowa-Zdroj",
  "Kutno",
  "Kwidzyn",
  "Lancut",
  "Lask",
  "Laziska Gorne",
  "Lebork",
  "Legionowo",
  "Legnica",
  "Leszno",
  "Leczyca",
  "Lezajsk",
  "Libiaz",
  "Lidzbark Warminski",
  "Limanowa",
  "Lipno",
  "Lodz",
  "Lomianki",
  "Lomza",
  "Lowicz",
  "Luban",
  "Lubaczow",
  "Lubartow",
  "Lubin",
  "Lubliniec",
  "Lublin",
  "Ledziny",
  "Lukow",
  "Malbork",
  "Marki",
  "Miechow",
  "Mielec",
  "Mikolow",
  "Milanowek",
  "Milicz",
  "Minsk Mazowiecki",
  "Mlawa",
  "Mogilno",
  "Mragowo",
  "Mszana Dolna",
  "Muszyna",
  "Myslenice",
  "Myslowice",
  "Myszkow",
  "Naklo nad Notecia",
  "Namyslow",
  "Niepolomice",
  "Nidzica",
  "Nisko",
  "Nowa Deba",
  "Nowa Ruda",
  "Nowa Sol",
  "Nowe Miasto Lubawskie",
  "Nowy Dwor Gdanski",
  "Nowy Dwor Mazowiecki",
  "Nowy Sacz",
  "Nowy Targ",
  "Nowy Tomysl",
  "Nysa",
  "Oborniki",
  "Olawa",
  "Olecko",
  "Olesnica",
  "Olesno",
  "Olkusz",
  "Olsztyn",
  "Olsztynek",
  "Opoczno",
  "Opole",
  "Opole Lubelskie",
  "Orneta",
  "Orzesze",
  "Osieczna",
  "Ostroleka",
  "Ostrow Mazowiecka",
  "Ostrow Wielkopolski",
  "Ostrowiec Swietokrzyski",
  "Ostrzeszow",
  "Oswiecim",
  "Otwock",
  "Ozarow Mazowiecki",
  "Pabianice",
  "Pajeczno",
  "Parczew",
  "Piaseczno",
  "Piastow",
  "Piekary Slaskie",
  "Pila",
  "Pinczow",
  "Pionki",
  "Pisz",
  "Pleszew",
  "Plock",
  "Plonsk",
  "Pniewy",
  "Poddebice",
  "Polkowice",
  "Poznan",
  "Prabuty",
  "Proszowice",
  "Prudnik",
  "Pruszcz Gdanski",
  "Pruszkow",
  "Przasnysz",
  "Przemysl",
  "Przeworsk",
  "Pszczyna",
  "Puck",
  "Pulawy",
  "Pultusk",
  "Puszczykowo",
  "Pyrzyce",
  "Pyskowice",
  "Rabka-Zdroj",
  "Raciaz",
  "Raciborz",
  "Radom",
  "Radomsko",
  "Radzionkow",
  "Radzymin",
  "Radzyn Podlaski",
  "Rawicz",
  "Rawa Mazowiecka",
  "Reda",
  "Ropczyce",
  "Ruda Slaska",
  "Rumia",
  "Rybnik",
  "Rydultowy",
  "Rypin",
  "Rzeszow",
  "Rzgow",
  "Sandomierz",
  "Sanok",
  "Sepolno Krajenskie",
  "Siedlce",
  "Siemianowice Slaskie",
  "Siemiatycze",
  "Sieradz",
  "Sierpc",
  "Skawina",
  "Skierniewice",
  "Skoczow",
  "Slupca",
  "Slupsk",
  "Sokolow Podlaski",
  "Solec Kujawski",
  "Sopot",
  "Sosnowiec",
  "Stalowa Wola",
  "Starachowice",
  "Stargard",
  "Starogard Gdanski",
  "Staszow",
  "Strzelce Opolskie",
  "Strzelin",
  "Strzelno",
  "Sucha Beskidzka",
  "Suchowola",
  "Sulejowek",
  "Sulecin",
  "Suwalki",
  "Swidnica",
  "Swidnik",
  "Swidwin",
  "Swiebodzice",
  "Swiebodzin",
  "Swiecie",
  "Swietochlowice",
  "Swinoujscie",
  "Szczecin",
  "Szczecinek",
  "Szczytno",
  "Szprotawa",
  "Sztum",
  "Szydlowiec",
  "Tarnobrzeg",
  "Tarnow",
  "Tarnowskie Gory",
  "Tczew",
  "Tomaszow Lubelski",
  "Tomaszow Mazowiecki",
  "Torun",
  "Trzcianka",
  "Trzebinia",
  "Trzebnica",
  "Tuchola",
  "Turek",
  "Tychy",
  "Ustka",
  "Ustron",
  "Wabrzezno",
  "Wadowice",
  "Wagrowiec",
  "Walbrzych",
  "Warszawa",
  "Warta",
  "Wejherowo",
  "Wieliczka",
  "Wielun",
  "Wieruszow",
  "Wodzislaw Slaski",
  "Wolomin",
  "Wroclaw",
  "Wrzesnia",
  "Wyszogrod",
  "Wyszkow",
  "Zabrze",
  "Zagorz",
  "Zagorze",
  "Zakopane",
  "Zambrow",
  "Zary",
  "Zawiercie",
  "Zbaszyn",
  "Zdunska Wola",
  "Zduny",
  "Zgierz",
  "Zgorzelec",
  "Zielona Gora",
  "Zlotoryja",
  "Zlotow",
  "Znin",
  "Zwolen",
  "Zyrardow",
  "Zywiec",
].sort();

export const DISPOSABLE_EMAIL_DOMAINS: Set<string> = new Set([
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "anonbox.net",
  "anonymbox.com",
  "binkmail.com",
  "bobmail.info",
  "brefmail.com",
  "bugmenot.com",
  "bumpymail.com",
  "burnermail.io",
  "chacuo.net",
  "clrmail.com",
  "cool.fr.nf",
  "correo.blogos.net",
  "cosmorph.com",
  "courrieltemporaire.com",
  "crazymailing.com",
  "cubiclink.com",
  "curryworld.de",
  "dayrep.com",
  "deadaddress.com",
  "despammed.com",
  "devnullmail.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dm.w3internet.co.uk",
  "dodgeit.com",
  "dodgit.com",
  "dontreg.com",
  "dontsendmespam.de",
  "drdrb.net",
  "dump-email.info",
  "dumpandjunk.com",
  "dumpmail.de",
  "dumpyemail.com",
  "e-mail.com",
  "e4ward.com",
  "emaildienst.de",
  "emailgo.de",
  "emailigo.de",
  "emailinfive.com",
  "emailmiser.com",
  "emailsensei.com",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emz.net",
  "enterto.com",
  "ephemail.net",
  "etranquil.com",
  "fakeinbox.com",
  "fakeinformation.com",
  "fakemail.fr",
  "fastacura.com",
  "filzmail.com",
  "fixmail.tk",
  "flurred.com",
  "flyspam.com",
  "garbagecollector.org",
  "garbagemail.org",
  "get2mail.fr",
  "getairmail.com",
  "getonemail.com",
  "getonemail.net",
  "gishpuppy.com",
  "goemailgo.com",
  "great-host.in",
  "greensloth.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "harakirimail.com",
  "hidemail.de",
  "hidzz.com",
  "hotpop.com",
  "ieh-mail.de",
  "imails.info",
  "inbucket.com",
  "inbox2.info",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "insorg-mail.info",
  "ipoo.org",
  "irish2me.com",
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "jnxjn.com",
  "jourrapide.com",
  "junk1.com",
  "kasmail.com",
  "kaspop.com",
  "klzlk.com",
  "kostenlosemailadresse.de",
  "kurzepost.de",
  "lawlita.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lol.ovpn.to",
  "lookugly.com",
  "lortemail.dk",
  "lr78.com",
  "maboard.com",
  "mail-temporaire.fr",
  "mail.by",
  "mail.mezimages.net",
  "mail.zp.ua",
  "mail2rss.org",
  "mailbidon.com",
  "mailblocks.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailin8r.com",
  "mailinater.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailincubator.com",
  "mailismagic.com",
  "mailmate.com",
  "mailme.ir",
  "mailme.lv",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnator.com",
  "mailnesia.com",
  "mailnull.com",
  "mailorg.org",
  "mailpick.biz",
  "mailrock.biz",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailzilla.com",
  "mailzilla.org",
  "makemetheking.com",
  "manifestgenerator.com",
  "mbx.cc",
  "mega.zik.dj",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "ministry-of-silly-walks.de",
  "mintemail.com",
  "mobi.web.id",
  "mohmal.com",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "monumentmail.com",
  "mt2015.com",
  "mx0.wwwnew.eu",
  "myalias.pw",
  "mycleaninbox.net",
  "myemailboxy.com",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantom.com",
  "mysamp.de",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "nabala.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtansen.de",
  "netmails.com",
  "netmails.net",
  "neverbox.com",
  "no-spam.ws",
  "noblepioneer.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.xl.cx",
  "nomail2me.com",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "nothingtoseehere.ca",
  "nowmymail.com",
  "nurfuerspam.de",
  "nus.edu.sg",
  "nwldx.com",
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "oneoffemail.com",
  "onewaymail.com",
  "oopi.org",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pjjkp.com",
  "plexolan.de",
  "pookmail.com",
  "privacy.net",
  "proxymail.eu",
  "prtnx.com",
  "putthisinyourspamdatabase.com",
  "qq.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "recursor.net",
  "regbypass.com",
  "remail.cf",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "sandelf.de",
  "saynotospams.com",
  "scatmail.com",
  "schafmail.de",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "sharklasers.com",
  "shieldedmail.com",
  "shiftmail.com",
  "shitmail.me",
  "shortmail.net",
  "sibmail.com",
  "skeefmail.com",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "slowslow.de",
  "slutty.horse",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakyaddress.com",
  "snkmail.com",
  "sofimail.com",
  "sofort-mail.de",
  "softpls.asia",
  "sogetthis.com",
  "soodonims.com",
  "spam4.me",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.info",
  "spambox.irishspringrealty.com",
  "spambox.us",
  "spamcero.com",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf",
  "spamfighter.ga",
  "spamfighter.gq",
  "spamfighter.ml",
  "spamfighter.tk",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrail.com",
  "spamtrap.ro",
  "speed.1s.fr",
  "spoofmail.de",
  "stuffmail.de",
  "super-auswahl.de",
  "supergreatmail.com",
  "supermailer.jp",
  "superrito.com",
  "superstachel.de",
  "suremail.info",
  "svk.jp",
  "sweetxxx.de",
  "tafmail.com",
  "tagyoureit.com",
  "talkinator.com",
  "tapchicuoihoi.com",
  "teewars.org",
  "temp-mail.org",
  "temp-mail.ru",
  "tempalias.com",
  "tempe4mail.com",
  "tempemail.biz",
  "tempemail.co.za",
  "tempemail.com",
  "tempemail.net",
  "tempinbox.com",
  "tempinbox.co.uk",
  "tempmail.eu",
  "tempmail.it",
  "tempmail2.com",
  "tempmaildemo.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempomail.fr",
  "temporarioemail.com.br",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tempthe.net",
  "thankdog.com",
  "thankyou2010.com",
  "thc.st",
  "thecriminals.com",
  "thisisnotmyrealemail.com",
  "thismail.net",
  "throwaway.email",
  "throwawayemailaddress.com",
  "tittbit.in",
  "tizi.com",
  "tmailinator.com",
  "toiea.com",
  "toomail.biz",
  "topranklist.de",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash2009.com",
  "trashdevil.com",
  "trashdevil.de",
  "trashemail.de",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashymail.com",
  "trashymail.net",
  "trbvm.com",
  "trbvn.com",
  "trialmail.de",
  "trickmail.net",
  "trillianpro.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "upliftnow.com",
  "uplipht.com",
  "venompen.com",
  "veryreallypermanent.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.info",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
  "whatiaas.com",
  "whatpaas.com",
  "whyspam.me",
  "wikidocuslice.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "wwwnew.eu",
  "x.ip6.li",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xmaily.com",
  "xoxy.net",
  "yapped.net",
  "yep.it",
  "yogamaven.com",
  "yomail.info",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.gq",
  "yopmail.net",
  "yourdomain.com",
  "ypmail.webarnak.fr.eu.org",
  "yuurok.com",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code.toUpperCase());
}

export function getPhoneCodeForCountry(code: string): string {
  const country = getCountryByCode(code);
  return country?.phoneCode ?? "";
}
